//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeadmin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class akademisyen
    {
        public int akademisyen_id { get; set; }
        public string akademisyen_ad { get; set; }
        public string akademisyen_soyad { get; set; }
        public string akademisyen_bolum { get; set; }
    }
}
