//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeadmin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class idari
    {
        public int idari_id { get; set; }
        public string idari_ad { get; set; }
        public string idari_soyad { get; set; }
        public Nullable<System.DateTime> idari_tarih { get; set; }
    }
}
