//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeadmin.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dbo_yemektarifEntities1 : DbContext
    {
        public Dbo_yemektarifEntities1()
            : base("name=Dbo_yemektarifEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ogrenciler> ogrenciler { get; set; }
        public virtual DbSet<akademisyen> akademisyen { get; set; }
        public virtual DbSet<idari> idari { get; set; }
    }
}
